<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../Tweeter.php';

/**
 * Test class for Tweeter.
 * Generated by PHPUnit on 2010-02-05 at 07:56:14.
 */
class TweeterTest extends PHPUnit_Framework_TestCase {
    /**
     * @var Tweeter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Tweeter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testTweet_text().
     */
    public function testTweet_text() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
?>
