<?php
require_once 'PHPUnit/Framework.php';

require_once dirname(__FILE__).'/../../WeatherApi.php';

/**
 * Test class for WeatherApi.
 * Generated by PHPUnit on 2010-02-05 at 07:56:11.
 */
class WeatherApiTest extends PHPUnit_Framework_TestCase {
    /**
     * @var WeatherApi
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WeatherApi;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGet_weather().
     */
    public function testGet_weather() {
        $weather = new WeatherApi();
        // ({start date}, {num days to recover})
        $weather->get_weather('2010-02-05',2);
        $this->assertTrue(true);
    }
}
?>
